<?xml version="1.0"?>
<package format="3">
  <name>pig_model</name>
  <version>1.0.0</version>
  <description>Independent asset package for simulated pigs</description>
  <maintainer email="your_email@nchu.edu.tw">vito</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>gazebo_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
